# Write a program, which has two print statements to print the following text (capital letters "O" and "H", made from "#" symbols)
# Pay attention that usage of spaces is forbidden, as well as creating the whole result text string using """ """, use '\n' and '\t' symbols instead.
print('#' * 9)
print("#\t\t#")
print("#\t\t#")
print("#\t\t#")
print('#' * 9)
print()
print("#\t\t#")
print("#\t\t#")
print('#' * 9)
print("#\t\t#")
print("#\t\t#")
